language: php

php:
  - 7.1
  - 7.2
#  - nightly

before_script:
  - travis_retry composer selfupdate
  - travis_retry composer i --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
